### ISSUE TITLE
Unable to create or edit a custom collection after importing MITRE ATT&CK default collections

### ISSUE THREAD

**Issue by Vayper** [center-for-threat-informed-defense/attack-workbench-frontend#287] opened 2022-02-18 16:13 UTC
Hi,
I'm attempting to make a new collection in ATT&CK Workbench, but it's not working.
When MITRE ATT&CK recommended collections are imported, creating or editing a new collection freezes with the _PREPARING CHANGE LISTS_ message: 

![bug](https://user-images.githubusercontent.com/7338706/154713550-a7952eb4-45d8-4b44-a637-63ecba40b21b.png)

<details>
<summary>Firefox console log</summary>
  
```log
ERROR TypeError: e[r.attackType] is undefined
    compareTo http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    __tryOrUnsub http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    observe http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    dispatch http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _execute http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    execute http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    flush http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    invokeTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    onInvokeTask http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    invokeTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    runTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    invokeTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    invoke http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    0 http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    setInterval handler*a http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    scheduleTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    onScheduleTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    scheduleTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    scheduleTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    scheduleMacroTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    f http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    r http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    o http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    requestAsyncId http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    schedule http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    schedule http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    schedule http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _schedule http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    scheduleNotification http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    next http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    e http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    __tryOrUnsub http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    notifyComplete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    _complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    complete http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    s http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    invokeTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    onInvokeTask http://localhost/main.55cb3d80ddbadae1ba8e.js:1
    invokeTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    runTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    invokeTask http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    _ http://localhost/polyfills.35a5ca1855eb057f016a.js:1
    k http://localhost/polyfills.35a5ca1855eb057f016a.js:1
main.55cb3d80ddbadae1ba8e.js:1:449396
```
</details>

<details>
<summary>docker-compose logs</summary>

```log
attack-workbench-rest-api            | 2022-02-18T15:26:15.642Z [HTTP] GET /api/collection-indexes 200 2.956 ms - -
attack-workbench-database            | {"t":{"$date":"2022-02-18T15:26:18.365+00:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn12","msg":"Slow query","attr":{"type":"command","ns":"attack-workspace.attackObjects","command":{"aggregate":"attackObjects","pipeline":[{"$sort":{"stix.id":1,"stix.modified":1}},{"$group":{"_id":"$stix.id","document":{"$last":"$$ROOT"}}},{"$replaceRoot":{"newRoot":"$document"}},{"$sort":{"stix.id":1}},{"$match":{}}],"cursor":{},"lsid":{"id":{"$uuid":"5558fc75-8aca-4d24-ab7a-5730db5e8e11"}},"$db":"attack-workspace"},"planSummary":"COLLSCAN","cursorid":8372546237693245867,"keysExamined":0,"docsExamined":17736,"hasSortStage":true,"numYields":35,"nreturned":101,"queryHash":"37EE910D","planCacheKey":"7CD809B8","reslen":340637,"locks":{"Global":{"acquireCount":{"r":44}},"Mutex":{"acquireCount":{"r":9}}},"storage":{},"remote":"172.23.0.3:50960","protocol":"op_msg","durationMillis":109}}
attack-workbench-collection-manager  | 2022-02-18T15:26:25.640Z [INFO] Scheduler running...
attack-workbench-rest-api            | 2022-02-18T15:26:25.645Z [HTTP] GET /api/collection-indexes 200 2.447 ms - -
attack-workbench-frontend            | 172.23.0.1 - - [18/Feb/2022:15:26:32 +0000] "GET /api/attack-objects?includeRevoked=true&includeDeprecated=true HTTP/1.1" 200 6832267 "http://localhost/collection/new?editing=true" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0"
attack-workbench-rest-api            | 2022-02-18T15:26:32.641Z [HTTP] GET /api/attack-objects?includeRevoked=true&includeDeprecated=true 200 13532.046 ms - -
```
</details>

# Steps to reproduce

1. Start the Workbench using the provided [docker-compose.yml](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/blob/master/docker-compose.yml)
2. Import the default MITRE ATT&CK collection index
3. Import the most recent version (10.1) of Enterprise collection. Following importation, I received this warning : 
  ```
    {
    "object_ref": "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168",
    "error_type": "Not in contents",
    "error_message": "Warning: Object in bundle but not in x_mitre_contents. Object will be saved in database."
  }
  ```
4.  Import the most recent version (10.1) of Mobile collection. I received the same warning as in step 3. Now, I can successfully navigate matrices, tactics, techniques, etc.
5.  Create a new collection using _COLLECTIONS_ -> _MY COLLECTIONS_ -> _CREATE A COLLECTION_. As shown in the screenshot, it becomes stuck.

# Additional details

- I tried on Firefox and Edge.
- I attempted to delete the object that was causing the warning in steps 3 and 4.
- If no MITRE ATT&CK collections have been imported previously, I **can** create a new collection. However, after importing the default collections, editing my previously created collection also freezes with the same error.

Thank you

**Comment by jimdeanmachine** [comment] 2022-02-22 19:43
Hey @Vayper , I'm having the exact same issue. I've tried setting up Workbench on a couple different machines and the issue persists. Also using Docker.

**Comment by clemiller** [comment] 2022-02-23 14:31
Hi @Vayper,

Thank you for reaching out and providing details! This is a known issue caused by a bug parsing ATT&CK object types when generating a new collection. We currently have a fix for this staged in [this open pull request](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/pull/276) (mentioned in the last line of the description). We plan to merge this feature in within the next week or two.

**Comment by clemiller** [comment] 2022-02-28 16:58
Fix for this issue is now staged on `develop`.

**Closed by clemiller** 2022-02-28 16:58 UTC
Labels: bug
