### ISSUE TITLE
Can't search by object ID?

### ISSUE THREAD

**Issue by dickens88** [center-for-threat-informed-defense/attack-workbench-frontend#229] opened 2021-07-20 01:36 UTC
Hi, 

I'm using workbench v1.0.1, it seems the search box can not search by object ID?

for example, when i'm trying to make my own collection, i need to select techniques, but there are so many options. I found there is a search box which should be very useful to me. but then i found it seems it can not search by technique ID ?

![image](https://user-images.githubusercontent.com/8390209/126248785-a9eea060-f992-4043-8948-adb33190d7b8.png)

the `T1087` is in the set, but when i type T1087 in the search box, it shows nothing. so i suggest to support searching by object ID here(just lisk MITTRE website did), it will save a lot of time when you trying to make your own collections. :)

**Comment by dickens88** [comment] 2021-07-20 02:32
In addition, it seems the search box also not support to search by other language word... for example, i created an item in Chinese `测试`, but i can't search by it's name.

![image](https://user-images.githubusercontent.com/8390209/126253210-6438d29e-1242-4c94-b00e-5de06b05dafe.png)

**Comment by isaisabel** [comment] 2021-07-20 12:58
Hi @dickens88,

The search system we use is somewhat limited at this time and doesn't include all object fields. It's also not terribly good at coming up with the correct results especially if there is a space in the query string -- for example the query `archive via utility` on Techniques won't show any results even though there is a technique with exactly that name.

The need to improve search results is documented in the REST API issue here: https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/issues/47

I'll add a comment there about the need for supporting additional languages and character sets. Since the search functionality is actually a REST API improvement I'm closing this issue so that it can be covered on that repository.

**Comment by isaisabel** [comment] 2021-07-20 12:58
Duplicate of https://github.com/center-for-threat-informed-defense/attack-workbench-rest-api/issues/47

**Closed by isaisabel** 2021-07-20 12:58 UTC
