### ISSUE TITLE
Can not download collections from COLLECTION INDEXES page

### ISSUE THREAD

**Issue by dickens88** [center-for-threat-informed-defense/attack-workbench-frontend#227] opened 2021-07-19 10:48 UTC
Hi, 
I'm new to this project, I'm trying to add something to workbench. I have added the preconfig collection index `MITRE ATT&CK` by clicking `+ ADD A COLLECTION INDEX` and i can saw a new record after that. but when i look into it and click the download button, for example 9.0 version, it will jump to `import a collection` page and show error `[object ProgressEvent]`. I don't understand what's that mean but i think it didn't download the data i want. bcos when i look into other modules like `TACTICS`, `MATRICES`, etc, nothing there.

![image](https://user-images.githubusercontent.com/8390209/126148701-a0e69040-3bf9-4da4-8e72-1b761e623910.png)

If someone can guide me about this issue, i will be very appreciate: )

**Comment by isaisabel** [comment] 2021-07-19 11:31
Hi @dickens88,

Your Workbench instance is having some sort of issue fetching or downloading that data -- the orange "snack-bar" on the bottom indicates an error has occurred. It's usually supposed to have a descriptive message there but for some reason that didn't happen in this case, so it's a bit tricky to tell what actually happened from the screenshot alone.

Can you please send us the contents of your javascript console? Errors would be mirrored there with additional detail. To show the console:
### Firefox
Tools -> Browser Tools -> Web Developer Tools, switch to the console tab
### Chrome
View -> Developer -> Javascript Console

The logs should look something like this, but in your case with more errors (red) most likely:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/28868888/126153675-5c345e3f-df9d-45ed-a238-beeafadada27.png">

**Comment by isaisabel** [comment] 2021-07-19 11:33
Once we figure out why your Workbench wasn't able to download the data I can also patch the error message to be more useful in the future.

**Comment by isaisabel** [comment] 2021-07-19 11:48
Another thing that occurred to me is that it _could_ be an issue with antivirus software blocking the download of the dataset due to a false positive (likely the same one as https://github.com/mitre/cti/issues/162). If you can download the Mobile or ICS datasets (which don't include that false positive) that would imply that this is the cause.

The workarounds for an antivirus blocking the download would be one of the following:
- Download the collection file manually (using the index [here](https://github.com/mitre-attack/attack-stix-data/blob/master/index.md) to find the correct file) and then upload the file into the application. The antivirus may still block the download even if you're doing it manually, but you might be able to get around it somehow.
- Add the URL/file to your antivirus's allow-list, or somehow configure your antivirus to stop blocking the download. I'm not sure how you would do this since it'd depend on which antivirus software you're using have.

**Comment by dickens88** [comment] 2021-07-19 13:25
@isaisabel thank you so much for your reply. The screenshot is as following.

![image](https://user-images.githubusercontent.com/8390209/126166492-861743b2-b4cf-4faa-a753-59f5e1c0fcc7.png)

just as you said, the issue is something related to my machine. i was using a web proxy, so it seems the connected was interuptted somehow. after i changed another machine and network, it works fine. 

but anyway, maybe you can optimize the error message to make the user easier to figure out where is the error. : )

**Comment by isaisabel** [comment] 2021-07-19 13:38
I'm glad you were able to get it working! I was able to replicate the error you were getting by disabling the REST API in the middle of an import, so I should be able to improve the error message using that.

**Comment by isaisabel** [comment] 2021-07-19 14:06
Error message display has been improved in #228 and will be released with the next release of `attack-workbench-frontend`. In the meantime you can check out the develop branch of this repository to get that improvement.

**Closed by isaisabel** 2021-07-19 14:06 UTC
Labels: bug

**Comment by isaisabel** [comment] 2021-07-19 14:09
FWIW this is what the error for this issue looks like with the fixed error messages:

![image](https://user-images.githubusercontent.com/28868888/126173250-bc0ce968-d9f8-40c3-b1aa-4e357885c136.png)
